import {getCurrentDateTime} from "./_getCurrentDateTime.js";
import {getMaxInArray} from "./_getMaxInArray.js";
import {getMinInArray} from "./_getMinInArray.js";
import {getNow} from "./_getNow.js";
import {getRandomNumberInRange} from "./_getRandomNumberInRange.js"
import {getStringFromArray} from "./_getStringFromArray.js";
import {getQuanntityInArray} from "./_getQuanntityInArray.js";
import {isArray} from "./_isArray.js";
import {isFunction} from "./_isFunction.js";
import {isObject} from "./_isObject.js";
import {isPalindrome} from "./_isPalindrome.js";
import {isValidNumber} from "./_isValidNumber.js";
import {setObjectIntoArray} from "./_setObjectIntoArray.js";
import {getSumOfArray} from "./_getSumOfArray.js";
import {isNull} from "./_isNull.js";
import {isUndefined} from "./_isUndefined.js";
import {isEmptyArray} from "./_isEmptyArray.js";
